exp_id: rvt2_lite_eight_hrp
tasks: push_buttons,slide_block_to_color_target,sweep_to_dustpan_of_size,meat_off_grill,turn_tap,place_shape_in_shape_sorter,close_jar,insert_onto_square_peg
bs: 3
num_workers: 3
epochs: 1
train_iterations: 10000
sample_distribution_mode: task_uniform

depth: 1
stage_one_depth: 8
stage_two_depth: 1
attn_dim: 512
ds_rate: 1.0
adapter: []
model: MVT_ViT
output_dim: 512
stage_two: true
rot_ver: 1
feat_ver: 1
cvx_up: true

pretrain: /home/paichichi/data/pretrain/HRP_IN.pth
overwriter_log_dir: /home/paichichi/projects/TCC-core/analysis/rvt2_lite/eight_runs/hrp
train_replay_storage_dir: /home/paichichi/data/rvt/train/replay/replay_train
data_folder: null
num_train: 10

peract:
  lr: 5.0e-5
  warmup_steps: 500
  optimizer_type: lamb
  lr_cos_dec: true
  lambda_weight_l2: 0.0001
  amp: true
  bnb: true
  transform_augmentation: true
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]

rvt:
  place_with_mean: false
  img_aug: 0.0
